language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.cache/bower
    - $HOME/.composer/cache
    - $HOME/.npm
    - /tmp/phantomjs
    - tools

env:
  global:
    - CORE_BRANCH=stable10-rename-integration-to-acceptance
    - APP_NAME=customgroups
  matrix:
    - DB=mysql

branches:
  only:
    - master

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

  # Add some output debugging information
  - cd ../core
  - ./occ check
  - ./occ status
  - ./occ app:list

script:
  - cd apps/$APP_NAME/
  - make $TEST

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - php: 7.1
      env: DB=mysql;CORE_BRANCH=rename-integration-to-acceptance
    - php: 7.2
      env: DB=mysql;CORE_BRANCH=rename-integration-to-acceptance
    # PHP unit tests + code coverage
    - php: 5.6
      env: DB=mysql;TEST=test-upload-coverage
    # PHP unit tests
    - php: 7.1
      env: DB=pgsql;TEST=test-php;CORE_BRANCH=rename-integration-to-acceptance
    - php: 5.6
      env: DB=pgsql;TEST=test-php;CORE_BRANCH=stable10-rename-integration-to-acceptance
    # Code checker / syntax
    - php: 7.1
      env: DB=mysql;TEST=test-codecheck;CORE_BRANCH=rename-integration-to-acceptance
    - php: 5.6
      env: DB=mysql;TEST=test-codecheck
    # Code checker (deprecations only, allowed to fail)
    - php: 5.6
      env: DB=mysql;TEST=test-codecheck-deprecations
    # Javascript tests
    - php: 7.1
      env: DB=mysql;TEST=test-js;CORE_BRANCH=rename-integration-to-acceptance
    - php: 5.6
      env: DB=mysql;TEST=test-js
    # Integration tests
    - php: 7.1
      env: DB=mysql;TEST=test-integration;CORE_BRANCH=rename-integration-to-acceptance
    - php: 5.6
      env: DB=mysql;TEST=test-integration;CORE_BRANCH=stable10-rename-integration-to-acceptance
  allow_failures:
    - env: DB=mysql;TEST=test-codecheck-deprecations
  fast_finish: true
